apiVersion: v1
kind: Service
metadata:
  name: conn-tracer-metrics
  namespace: kube-system
  labels:
    name: conn-tracer
spec:
  selector:
    name: conn-tracer
  ports:
    - name: http-metrics
      protocol: TCP
      port: 8001
      targetPort: 8001